fixing(AttributeError: partially initialized module 'random' has no attribute 'randint' (most likely due to a circular import)) error by changing file name